### ISSUE TITLE
VVebo修复脚本相关

### ISSUE THREAD

**Issue by iiiuo** [androidcn/userscripts#1]
> 2024/01/29 14:39:56:216  <error>      [JS Console]: [Exception]: Can't find variable: $persistentStore.
2024/01/29 14:39:56:226  <error>      [JS Console]: Exception Can't find variable: $persistentStore, https://raw.githubusercontent.com/suiyuran/stash/main/scripts/fix-vvebo-user-timeline.js

你好，在使用Quantumult X的重写脚本后日志里会出现很多次这样的记录，是因为转换有问题吗？

**Comment by androidcn** [comment]
是否是 最新 QX TF 版？

**Comment by androidcn** [comment]
@iiiuo 重新刷新一下脚本，重新适配了 新脚本

**Comment by iiiuo** [comment]
已修复，感谢
