### ISSUE TITLE
请教大佬这个Asspp_Pro相关的怎么用啊，想修复下

### ISSUE THREAD

**Issue by songxing10000** [androidcn/userscripts#4]
Asspp_Pro.js 和AssppProFix.plugin 怎么用啊

**Comment by androidcn** [comment]
> Asspp_Pro.js 和AssppProFix.plugin 怎么用啊

这是解决版本号无法获取的插件

**Comment by songxing10000** [comment]
我知道是解决那个问题的，但是怎么用啊，现在我也获取不了版本号

**Comment by songxing10000** [comment]
居然可以了，把Asspp_Pro.js放到Storm Sniffer中就可以了

**Comment by androidcn** [comment]
> 居然可以了，把Asspp_Pro.js放到Storm Sniffer中就可以了

我是为了Loon而写的，没测试过其他，不过理论上适合所有QX LOON SURGE

**Comment by Sokach8** [comment]
大佬可以教一下我吗 Asspp pro

**Comment by androidcn** [comment]
> 大佬可以教一下我吗 Asspp pro

这个app已经废了 没用了

**Comment by Sokach8** [comment]
好的 感谢大佬

androidcn ***@***.***>于2025年7月30日 周三22:17写道：
